### ISSUE TITLE
Exception transformer

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tablebot#39]
Include a simple function that runs a computation, and if it throws uses a provided function to throw a different exception.

`transformException :: (Exception e, Exception e', MonadExcept m) => m a -> (e -> e') -> m a` would be the relevant type signature I think.

**Comment by distributive** [comment]
I said I'd do this next week but actually it's already done and will be in the next version of my pr.

Notably I've restricted the exception type to `BotException` and added a constant version which just replaces all exceptions with some constant exception.
