### ISSUE TITLE
Reminder Plugin Improvements

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tablebot#4]
There is already a reminder plugin provided in `Tablebot.Plugins.Reminder`. This is fairly rudimentary and could be improved.

- [ ] Use the user's timezone as to correctly remind them. Still store this in the database as UTC, but you'll need to determine the timezone and change their inputted date/time accordingly.
- [x] Accept formats other than `DD/MM/YYYY HH:MM`. Some ideas follow, although you might want to look at what Haskell's `duckling` package can provide.
    - [x] Just a date, defaulting to midday.
    - [x] Days such as "on the 21st" which autofill month and year.
    - [x] Relative datetimes, such as "in ten hours".
- [ ] Allow users to delete their own reminders.

Other ideas are of course welcome, but these are a few I thought of.

**Comment by L0neGamer** [comment]
Some of this is covered in https://github.com/WarwickTabletop/tablebot/pull/37.

**Comment by finnbar** [comment]
Closing in favour of #96
