### ISSUE TITLE
Provide an easy way to run a DatabaseDiscord () on bot startup per plugin

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tablebot#41]
Some plugins work with config data that needs to be loaded from file (such as Reminder's duckling data), and end up loading that data on every command invocation. This should likely be avoided.

You may want to add one more part to a Plugin - startEvents, which all fire when a plugin is started.

**Comment by the-Bruce** [comment]
We didn't end up running a full DatabaseDiscord, but you can now run a Database on start up as a result of #46
