### ISSUE TITLE
Shibe plugin

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tablebot#49]
UB3RBOT's `.shibe` has become popular recently. Implement it.
`.shibe` should summon an image of a Shibe and nothing else. You may want to look at the implementation of the Cat command for ideas, although you may be able to avoid the API key stuff depending on how accessing shibe images works.

![An example call of `.shibe`. It produces a lovely shibe.](https://user-images.githubusercontent.com/4217801/141683752-f689d16f-52ea-4607-b0c2-179192bf3e08.png)

**Comment by L0neGamer** [comment]
Cats plugin can be found here: <https://github.com/WarwickTabletop/tablebot/blob/main/src/Tablebot/Plugins/Cats.hs>.
