### ISSUE TITLE
Smart Command Maybe parsing doesn't work as expected

### ISSUE THREAD

**Issue by L0neGamer** [WarwickTabletop/tablebot#69]
Using SmartCommands, one can automatically parse out certain values. However, this doesn't work as expected for the case where one has multiple Maybe values to parse; it breaks.

This file exhibits a case where this does not work: https://github.com/L0neGamer/tablebot/blob/smartcommand-maybe/src/Tablebot/Plugins/BrokenCase.hs.

In the case where both values are provided, the parser and function operates fine.
![image](https://user-images.githubusercontent.com/10566848/145205012-5180263a-7316-4691-8710-68607bac237a.png)

However, if either value is missing, or both, the parsing fails.
![image](https://user-images.githubusercontent.com/10566848/145205133-5ee19ce0-d098-4038-a757-3e4283b5bd2a.png)
![image](https://user-images.githubusercontent.com/10566848/145205147-6033b587-0696-49a9-a299-a94e8a76877f.png)
![image](https://user-images.githubusercontent.com/10566848/145205173-8ba7a797-35a3-4f61-b6b3-456cc8db5e6d.png)

I believe the issue is to do with the use of `skipSpace1` in the recursive case of SmartCommands. Every time an argument is parsed, the SmartCommand expects there to be one (or more) spaces following it; but in the case of Maybe values, there may not have been an argument parsed, so there may not be space values to parse afterwards. Additionally, there may be cases where the second argument is a Maybe, and thus `eof` is found where one or more spaces are expected. (I have half-confirmed this theory by adding an error case to `skipSpace1`, and running the example above)

As to solutions, I'm not too sure. The first that comes to mind is making custom SmartCommand cases in the case of Maybe, but having tried that the compiler complains about overlapping instances.

**Comment by samcoy3** [comment]
Working on this -- will PR tomorrow.
