### ISSUE TITLE
.flip doesn't like quoted strings

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tablebot#95]
If you do something like `.flip "option 1" "option 2"`, it will select from `"option`, `1"`, `"option"` and `2"`. This... isn't great behaviour.

You may need to change the SmartCommand type to something like `Either Text Quoted` and go from there.

**Comment by samcoy3** [comment]
What's the desired behaviour for `$flip "1 2 3` (i.e. a hanging quote)? User-facing error, or accepting `"1` as an option?

**Comment by distributive** [comment]
I'd say accept `"1` as the option - it's better to accept a few erroneous inputs that reject the occasional intentional one

**Comment by distributive** [comment]
By accept `"1` I of course mean option (2)
