### ISSUE TITLE
Outdated file and module names in tutorial

### ISSUE THREAD

**Issue by samcoy3** [WarwickTabletop/tablebot#98]
It seems that some of the module names in `tutorials/1.Plugins.md` are out of date (in particular it seems that `Tablebot.Plugin.*` no longer exists as a namespace). It would be useful to update this (although it isn't too large an issue as it's fairly obvious where the modules have gone, I suspect).

**Comment by the-Bruce** [comment]
I'm currently 90% of the way through fixing this already. Will push soon with corrected versions

**Comment by the-Bruce** [comment]
For reference while I'm doing it, `Tablebot.Plugin.*` -> `Tablebot.Utility.*`, and `Tablebot.Handler.*` -> `Tablebot.Internal.*`

**Comment by finnbar** [comment]
Resolved by #99
